[phases.setup]
nixPkgs = [
    'php82',
    'php82Packages.composer',
    'php82Extensions.mbstring',
    'php82Extensions.pdo',
    'php82Extensions.pdo_mysql',
    'php82Extensions.tokenizer',
    'php82Extensions.xml',
    'php82Extensions.ctype',
    'php82Extensions.fileinfo',
    'php82Extensions.bcmath',
    'php82Extensions.gd',
    'nodejs'
]

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-scripts --no-interaction',
    'npm ci --prefer-offline --no-audit'
]

[phases.build]
cmds = [
    'npm run build',
    'composer install --optimize-autoloader --no-dev --no-scripts',
    'npm prune --omit=dev',
    'rm -rf node_modules/.cache',
    'rm -rf .npm',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'

